### PR TITLE
New lunch options

### PR DESCRIPTION
**Pull request by blamattina**
cc @wsorenson

### CODE REVIEW

**Comment by tpetr** [comment]
🚢

**Review by kj800x — APPROVED** [review]
LGTM 🚢 🎉

**Review by jmp3833 — CHANGES_REQUESTED** [review]
@blamattina I don't see Tahaza Hummus Kitchen here

cc @chpeters @mgreene

**Comment by chpeters** [comment]
Hot take: Tahaza is hellscape territory. @bent0b0x

**Comment by mgreene** [comment]
Disruptive if true

**Comment by wolfgangcodes** [comment]
🌮

**Pull request closed without merging**
